version: 0.2

phases:
pre_build:
commands:
- echo Logging into Amazon ECR
- aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 327512371512.dkr.ecr.ap-south-1.amazonaws.com
- aws eks update-kubeconfig --region ap-south-1 --name brain-cluster

build:
commands:
- docker build -t brain-tasks-app .
- docker tag brain-tasks-app:latest 327512371512.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest

post_build:
commands:
- docker push 327512371512.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest
- kubectl apply -f deployment.yaml
- kubectl apply -f service.yaml

